### ISSUE TITLE
Many terms appear to be filenames

### ISSUE THREAD

**Issue by danluu** [BitFunnel/Workbench#10]
~~~
58824d7fb6a6fae3,1,1,4.61273e-07,mp_photo_guidelines.html
65f2c1768fda3aaa,1,0,4.61273e-07,engineering.svg
48f47d14ac8f85df,1,0,0.00314992,cover.jpg
39cf0dcb77b80dd8,1,0,0.000296944,filmposter.jpeg
44cd8472a0872e66,1,0,0.00436699,logo.png
~~~

**Comment by MikeHopcroft** [comment]
filmposter.jpeg actually appears in https://pt.wikipedia.org/wiki/O_Amor_Natural_(filme).
mp_photo_guidelines.html actually appears in https://en.wikipedia.org/wiki/File:Marshole.jpg.

It seems fairly common for Wikipedia pages to include file names in captions and as link text.
