### ISSUE TITLE
Dates don't appear to be normalized

### ISSUE THREAD

**Issue by danluu** [BitFunnel/Workbench#12]
~~~
ba3f1d7af1500bd9,1,1,1.15318e-07,19.06.2002
2ed60e759534c745,1,1,1.15318e-07,1915aug10a
~~~

We also have nothing with `/`, which may mean that we're incorrectly splitting up dates with slashes in them.

**Comment by MikeHopcroft** [comment]
1915aug10a is the name of an eclipse at https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Eclipses/Work_Page.

19.06.2012 is in a caption in https://en.m.wikipedia.org/wiki/File:Wesselburenkraut_19.06.2012_18-35-26.jpg.
