### ISSUE TITLE
Terms prefixed with numbers

### ISSUE THREAD

**Issue by danluu** [BitFunnel/Workbench#15]
~~~
ff30dd2be245a4d4,1,1,1.15318e-07,22raggedy
e06a3c2008939008,1,1,1.15318e-07,269life
~~~

**Comment by MikeHopcroft** [comment]
22raqggedy is part of a url that is used as link text in https://en.wikipedia.org/wiki/Wikipedia:Reference_desk/Archives/Entertainment/2009_September_18.

269life is on the page https://en.wikipedia.org/wiki/Calf_269.
